[phases.setup]
nixPkgs = [
  "nodejs",
  "chromium",
  "glib",
  "nss",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "libdrm",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "alsa-lib",
  "pango",
  "cairo"
]

[start]
cmd = "node index.js"
